import pyautogui
import time

#print(pyautogui.mouseInfo())
# How many sugercane accounts are running and how many wart accounts are running
sugerInstances = 5
wartInstances = 0
#This is where u define termination timer, how long you want the scripts to run for, starts after everything is up and running.
terminationTimer = 86400
# all of the accounts are stored in the format of "email", "password", "proxyip"
# These are all of the sugar cane accounts, assuming 20 in total.
s1 = "", "", ""
s2 = "", "", ""
s3 = "", "", ""
s4 = "", "", ""
s5 = "", "", ""
s6 = "", "", ""
s7 = "", "", ""
s8 = "", "", ""
s9 = "", "", ""
s10 = "", "", ""
s11 = "", "", ""
s12 = "", "", ""
# s13 = "", "", ""
# s14 = "", "", ""
# s15 = "", "", ""
# s16 = "", "", ""
# s17 = "", "", ""
# s18 = "", "", ""
# s19 = "", "", ""
# s20 = "", "", ""

# These are all of the netherwart accounts

# w17 = "", "", ""
# w18 = "", "", ""
# w19 = "", "", ""
# w20 = "", "", ""

accountNumber = sugerInstances + wartInstances
minecraft = 1856, 914
accountButton = 1000, 60
logout = 987, 167
microsoftLogin = 1412, 287
signIn = 880, 549
signInNext = 1165, 680
password = 883, 620
passwordSignIn = 1168, 709

letsGo = 1040, 857
proxyButton = 1259, 349
IPPort = 813, 423
proxyApply = 876, 683
startAnyway = 1595, 418
playButton = 1500, 500
errorButton = 1266, 599
multiplayerButton = 959, 584
hypixel = 702, 421
loop = True

def paste(x):
    pyautogui.typewrite(x)


def sugercane():
    pyautogui.moveTo(minecraft[0], minecraft[1])
    pyautogui.doubleClick(minecraft[0], minecraft[1])
    # Clicks play button
    time.sleep(20)
    pyautogui.keyDown('winleft')
    pyautogui.keyUp('winleft')
    pyautogui.moveTo(accountButton[0], accountButton[1])
    time.sleep(1)
    pyautogui.click(accountButton[0], accountButton[1])
    time.sleep(5)
    pyautogui.moveTo(logout[0], logout[1])
    pyautogui.click(logout[0], logout[1])
    time.sleep(10)
    pyautogui.moveTo(microsoftLogin[0], microsoftLogin[1])
    pyautogui.click(microsoftLogin[0], microsoftLogin[1])
    time.sleep(15)
    pyautogui.moveTo(signIn[0], signIn[1])
    pyautogui.click(signIn[0], signIn[1])
    paste(s1[0])
    time.sleep(5)
    pyautogui.moveTo(signInNext[0], signInNext[1])
    pyautogui.click(signInNext[0], signInNext[1])
    time.sleep(10)
    pyautogui.moveTo(password[0], password[1])
    pyautogui.click(password[0], password[1])
    paste(s1[1])
    pyautogui.moveTo(passwordSignIn[0], passwordSignIn[1])
    pyautogui.click(passwordSignIn[0], passwordSignIn[1])
    time.sleep(25)
    pyautogui.moveTo(letsGo[0], letsGo[1])
    pyautogui.click(letsGo[0], letsGo[1])
    time.sleep(20)
    pyautogui.moveTo(playButton[0], playButton[1])
    pyautogui.click(playButton[0], playButton[1])
    time.sleep(120)
    pyautogui.moveTo(errorButton[0], errorButton[1])
    pyautogui.click(errorButton[0], errorButton[1])
    time.sleep(2)
    pyautogui.moveTo(multiplayerButton[0], multiplayerButton[1])
    pyautogui.click(multiplayerButton[0], multiplayerButton[1])
    time.sleep(2)
    pyautogui.moveTo(proxyButton[0], proxyButton[1])
    pyautogui.click(proxyButton[0], proxyButton[1])
    time.sleep(2)
    pyautogui.moveTo(IPPort[0], IPPort[1])
    pyautogui.click(IPPort[0], IPPort[1])
    pyautogui.keyDown('ctrl')
    pyautogui.press('a')
    pyautogui.keyUp('ctrl')
    pyautogui.press('del')
    time.sleep(.1)
    paste(s1[2])
    time.sleep(1)
    pyautogui.moveTo(proxyApply[0], proxyApply[1])
    pyautogui.click(proxyApply[0], proxyApply[1])
    time.sleep(5)
    pyautogui.moveTo(hypixel[0], hypixel[1])
    pyautogui.click(hypixel[0], hypixel[1])
    while not (pyautogui.pixelMatchesColor(961, 774, (167, 110, 31))):
        time.sleep(1)

    pyautogui.press('4')
    time.sleep(.25)
    pyautogui.click()
    time.sleep(.25)
    time.sleep(2)
    pyautogui.keyDown('del')
    pyautogui.keyDown('end')
    pyautogui.keyUp('del')
    pyautogui.keyUp('end')
    time.sleep(2)
    pyautogui.press('k')
    time.sleep(.25)
    pyautogui.press('0')
    time.sleep(.25)
    pyautogui.press('enter')
    pyautogui.keyDown('winleft')
    pyautogui.keyUp('winleft')
    pyautogui.moveTo(956, 309)
    pyautogui.dragRel(-550, 0, duration=0.2)
    time.sleep(5)

def sugarcaneMulti(user, passwords, ip):
    pyautogui.moveTo(minecraft[0], minecraft[1])
    pyautogui.doubleClick(minecraft[0], minecraft[1])
    # Clicks play button
    time.sleep(30)
    pyautogui.keyDown('winleft')
    pyautogui.keyUp('winleft')
    pyautogui.moveTo(accountButton[0], accountButton[1])
    pyautogui.click(accountButton[0], accountButton[1])
    time.sleep(10)
    pyautogui.moveTo(logout[0], logout[1])
    pyautogui.click(logout[0], logout[1])
    time.sleep(10)
    pyautogui.moveTo(microsoftLogin[0], microsoftLogin[1])
    pyautogui.click(microsoftLogin[0], microsoftLogin[1])
    time.sleep(20)
    pyautogui.moveTo(signIn[0], signIn[1])
    pyautogui.click(signIn[0], signIn[1])
    paste(user[0])
    time.sleep(5)
    pyautogui.moveTo(signInNext[0], signInNext[1])
    pyautogui.click(signInNext[0], signInNext[1])
    time.sleep(10)
    pyautogui.moveTo(password[0], password[1])
    pyautogui.click(password[0], password[1])
    paste(passwords[1])
    time.sleep(10)
    pyautogui.moveTo(passwordSignIn[0], passwordSignIn[1])
    pyautogui.click(passwordSignIn[0], passwordSignIn[1])
    pyautogui.moveTo(1163,726)
    pyautogui.click(1163,726)
    time.sleep(20)
    pyautogui.moveTo(letsGo[0], letsGo[1])
    pyautogui.click(letsGo[0], letsGo[1])
    time.sleep(20)
    pyautogui.moveTo(playButton[0], playButton[1])
    pyautogui.click(playButton[0], playButton[1])
    time.sleep(10)
    pyautogui.moveTo(startAnyway[0], startAnyway[1])
    pyautogui.click(startAnyway[0], startAnyway[1])
    time.sleep(130)
    pyautogui.moveTo(errorButton[0], errorButton[1])
    pyautogui.click(errorButton[0], errorButton[1])
    time.sleep(2)
    pyautogui.moveTo(multiplayerButton[0], multiplayerButton[1])
    pyautogui.click(multiplayerButton[0], multiplayerButton[1])
    time.sleep(2)
    pyautogui.moveTo(proxyButton[0], proxyButton[1])
    pyautogui.click(proxyButton[0], proxyButton[1])
    time.sleep(2)
    pyautogui.moveTo(IPPort[0], IPPort[1])
    pyautogui.click(IPPort[0], IPPort[1])
    pyautogui.keyDown('ctrl')
    pyautogui.press('a')
    pyautogui.keyUp('ctrl')
    pyautogui.press('del')
    time.sleep(.1)
    paste(ip[2])
    time.sleep(1)
    pyautogui.moveTo(proxyApply[0], proxyApply[1])
    pyautogui.click(proxyApply[0], proxyApply[1])
    time.sleep(5)
    pyautogui.moveTo(hypixel[0], hypixel[1])
    pyautogui.click(hypixel[0], hypixel[1])
    while not (pyautogui.pixelMatchesColor(961, 774, (167, 110, 31))):
        time.sleep(1)
    time.sleep(1)
    pyautogui.press('4')
    time.sleep(.25)
    pyautogui.click()
    time.sleep(.25)
    time.sleep(2)
    pyautogui.keyDown('del')
    pyautogui.keyDown('end')
    pyautogui.keyUp('del')
    pyautogui.keyUp('end')
    time.sleep(2)
    pyautogui.press('k')
    time.sleep(.25)
    pyautogui.press('0')
    time.sleep(.25)
    pyautogui.press('enter')
    pyautogui.press('enter')
    pyautogui.keyDown('winleft')
    pyautogui.keyUp('winleft')
    pyautogui.moveTo(956, 309)
    pyautogui.dragRel(-550, 0, duration=0.2)
    time.sleep(5)

def wart():
    pyautogui.moveTo(minecraft[0], minecraft[1])
    pyautogui.doubleClick(minecraft[0], minecraft[1])
    # Clicks play button
    time.sleep(30)
    pyautogui.keyDown('winleft')
    pyautogui.keyUp('winleft')
    time.sleep(1)
    pyautogui.moveTo(accountButton[0], accountButton[1])
    pyautogui.click(accountButton[0], accountButton[1])
    time.sleep(10)
    pyautogui.moveTo(logout[0], logout[1])
    pyautogui.click(logout[0], logout[1])
    time.sleep(10)
    pyautogui.moveTo(microsoftLogin[0], microsoftLogin[1])
    pyautogui.click(microsoftLogin[0], microsoftLogin[1])
    time.sleep(20)
    pyautogui.moveTo(signIn[0], signIn[1])
    pyautogui.click(signIn[0], signIn[1])
    paste(w1[0])
    time.sleep(5)
    pyautogui.moveTo(signInNext[0], signInNext[1])
    pyautogui.click(signInNext[0], signInNext[1])
    time.sleep(10)
    pyautogui.moveTo(password[0], password[1])
    pyautogui.click(password[0], password[1])
    paste(w1[1])
    pyautogui.moveTo(passwordSignIn[0], passwordSignIn[1])
    pyautogui.click(passwordSignIn[0], passwordSignIn[1])
    time.sleep(20)
    pyautogui.moveTo(letsGo[0], letsGo[1])
    pyautogui.click(letsGo[0], letsGo[1])

    time.sleep(20)
    pyautogui.moveTo(startAnyway[0], startAnyway[1])
    pyautogui.click(startAnyway[0], startAnyway[1])
    time.sleep(5)
    pyautogui.moveTo(playButton[0], playButton[1])
    pyautogui.click(playButton[0], playButton[1])
    time.sleep(130)
    pyautogui.moveTo(errorButton[0], errorButton[1])
    pyautogui.click(errorButton[0], errorButton[1])
    time.sleep(2)
    pyautogui.moveTo(multiplayerButton[0], multiplayerButton[1])
    pyautogui.click(multiplayerButton[0], multiplayerButton[1])
    time.sleep(2)
    pyautogui.moveTo(proxyButton[0], proxyButton[1])
    pyautogui.click(proxyButton[0], proxyButton[1])
    time.sleep(2)
    pyautogui.moveTo(IPPort[0], IPPort[1])
    pyautogui.click(IPPort[0], IPPort[1])
    pyautogui.keyDown('ctrl')
    pyautogui.press('a')
    pyautogui.keyUp('ctrl')
    pyautogui.press('del')
    time.sleep(1)
    paste(w1[2])
    time.sleep(1)
    pyautogui.moveTo(proxyApply[0], proxyApply[1])
    pyautogui.click(proxyApply[0], proxyApply[1])
    time.sleep(5)
    pyautogui.moveTo(hypixel[0], hypixel[1])
    pyautogui.click(hypixel[0], hypixel[1])
    while not (pyautogui.pixelMatchesColor(961, 774, (167, 110, 31))):
        time.sleep(1)

    pyautogui.press('4')
    time.sleep(.25)
    pyautogui.click()
    time.sleep(.25)
    time.sleep(2)
    pyautogui.keyDown('del')
    pyautogui.keyDown('end')
    pyautogui.keyUp('del')
    pyautogui.keyUp('end')
    time.sleep(2)
    pyautogui.press('p')
    time.sleep(.25)
    pyautogui.press('0')
    time.sleep(.25)
    pyautogui.press('enter')
    pyautogui.press('enter')
    pyautogui.keyDown('winleft')
    pyautogui.keyUp('winleft')
    pyautogui.moveTo(956, 309)
    pyautogui.dragRel(-550, 0, duration=0.2)
    time.sleep(5)

def wartMulti(user, passwords, ip):
    pyautogui.moveTo(minecraft[0], minecraft[1])
    pyautogui.doubleClick(minecraft[0], minecraft[1])
    # Clicks play button
    time.sleep(30)
    pyautogui.keyDown('winleft')
    pyautogui.keyUp('winleft')
    time.sleep(1)
    pyautogui.moveTo(accountButton[0], accountButton[1])
    pyautogui.click(accountButton[0], accountButton[1])
    time.sleep(10)
    pyautogui.moveTo(logout[0], logout[1])
    pyautogui.click(logout[0], logout[1])
    time.sleep(10)
    pyautogui.moveTo(microsoftLogin[0], microsoftLogin[1])
    pyautogui.click(microsoftLogin[0], microsoftLogin[1])
    time.sleep(20)
    pyautogui.moveTo(signIn[0], signIn[1])
    pyautogui.click(signIn[0], signIn[1])
    paste(user[0])
    time.sleep(5)
    pyautogui.moveTo(signInNext[0], signInNext[1])
    pyautogui.click(signInNext[0], signInNext[1])
    time.sleep(10)
    pyautogui.moveTo(password[0], password[1])
    pyautogui.click(password[0], password[1])
    paste(passwords[1])
    time.sleep(10)
    pyautogui.moveTo(passwordSignIn[0], passwordSignIn[1])
    pyautogui.click(passwordSignIn[0], passwordSignIn[1])
    pyautogui.moveTo(1163,726)
    pyautogui.click(1163,726)
    time.sleep(20)
    pyautogui.moveTo(letsGo[0], letsGo[1])
    pyautogui.click(letsGo[0], letsGo[1])
    time.sleep(20)
    pyautogui.moveTo(playButton[0], playButton[1])
    pyautogui.click(playButton[0], playButton[1])
    time.sleep(10)
    pyautogui.moveTo(startAnyway[0], startAnyway[1])
    pyautogui.click(startAnyway[0], startAnyway[1])
    time.sleep(130)
    pyautogui.moveTo(errorButton[0], errorButton[1])
    pyautogui.click(errorButton[0], errorButton[1])
    time.sleep(2)
    pyautogui.moveTo(multiplayerButton[0], multiplayerButton[1])
    pyautogui.click(multiplayerButton[0], multiplayerButton[1])
    time.sleep(2)
    pyautogui.moveTo(proxyButton[0], proxyButton[1])
    pyautogui.click(proxyButton[0], proxyButton[1])
    time.sleep(2)
    pyautogui.moveTo(IPPort[0], IPPort[1])
    pyautogui.click(IPPort[0], IPPort[1])
    pyautogui.keyDown('ctrl')
    pyautogui.press('a')
    pyautogui.keyUp('ctrl')
    pyautogui.press('del')
    time.sleep(.1)
    paste(ip[2])
    time.sleep(1)
    pyautogui.moveTo(proxyApply[0], proxyApply[1])
    pyautogui.click(proxyApply[0], proxyApply[1])
    time.sleep(5)
    pyautogui.moveTo(hypixel[0], hypixel[1])
    pyautogui.click(hypixel[0], hypixel[1])
    while not (pyautogui.pixelMatchesColor(961, 774, (167, 110, 31))):
        time.sleep(1)
    time.sleep(1)
    pyautogui.press('4')
    time.sleep(.25)
    pyautogui.click()
    time.sleep(.25)
    time.sleep(2)
    pyautogui.keyDown('del')
    pyautogui.keyDown('end')
    pyautogui.keyUp('del')
    pyautogui.keyUp('end')
    time.sleep(2)
    pyautogui.press('p')
    time.sleep(.25)
    pyautogui.press('0')
    time.sleep(.25)
    pyautogui.press('enter')
    pyautogui.press('enter')
    pyautogui.keyDown('winleft')
    pyautogui.keyUp('winleft')
    pyautogui.moveTo(956, 309)
    pyautogui.dragRel(-550, 0, duration=0.2)
    time.sleep(5)

def termination():
    screenWidth, screenHeight = pyautogui.size()
    pyautogui.moveTo(screenWidth / 2, screenHeight / 2)
    pyautogui.click(screenWidth / 2, screenHeight / 2)
    pyautogui.keyDown('alt')
    pyautogui.keyDown('f4')
    pyautogui.keyUp('alt')
    pyautogui.keyUp('f4')
    pyautogui.moveTo(904,1055)
    pyautogui.rightClick(904,1055)
    pyautogui.moveTo(784, 1010)
    pyautogui.leftClick(784, 1010)
    time.sleep(1)
    pyautogui.moveTo(screenWidth / 2, screenHeight / 2)
    pyautogui.click(screenWidth / 2, screenHeight / 2)
    pyautogui.keyDown('alt')
    pyautogui.keyDown('f4')
    pyautogui.keyUp('alt')
    pyautogui.keyUp('f4')


while (loop == True):
    time.sleep(5)
    if (sugerInstances == 0 and wartInstances == 0):
        termination()
    if (sugerInstances == 1):
        sugercane()
    if (sugerInstances == 2):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
    if (sugerInstances == 3):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
    if (sugerInstances == 4):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
        sugarcaneMulti(s4, s4, s4)
    if (sugerInstances == 5):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
        sugarcaneMulti(s4, s4, s4)
        sugarcaneMulti(s5, s5, s5)
    if (sugerInstances == 6):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
        sugarcaneMulti(s4, s4, s4)
        sugarcaneMulti(s5, s5, s5)
        sugarcaneMulti(s6, s6, s6)
    if (sugerInstances == 7):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
        sugarcaneMulti(s4, s4, s4)
        sugarcaneMulti(s5, s5, s5)
        sugarcaneMulti(s6, s6, s6)
        sugarcaneMulti(s7, s7, s7)
    if (sugerInstances == 8):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
        sugarcaneMulti(s4, s4, s4)
        sugarcaneMulti(s5, s5, s5)
        sugarcaneMulti(s6, s6, s6)
        sugarcaneMulti(s7, s7, s7)
        sugarcaneMulti(s8, s8, s8)
    if (sugerInstances == 9):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
        sugarcaneMulti(s4, s4, s4)
        sugarcaneMulti(s5, s5, s5)
        sugarcaneMulti(s6, s6, s6)
        sugarcaneMulti(s7, s7, s7)
        sugarcaneMulti(s8, s8, s8)
        sugarcaneMulti(s9, s9, s9)
    if (sugerInstances == 10):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
        sugarcaneMulti(s4, s4, s4)
        sugarcaneMulti(s5, s5, s5)
        sugarcaneMulti(s6, s6, s6)
        sugarcaneMulti(s7, s7, s7)
        sugarcaneMulti(s8, s8, s8)
        sugarcaneMulti(s9, s9, s9)
        sugarcaneMulti(s10, s10, s10)
    if (sugerInstances == 11):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
        sugarcaneMulti(s4, s4, s4)
        sugarcaneMulti(s5, s5, s5)
        sugarcaneMulti(s6, s6, s6)
        sugarcaneMulti(s7, s7, s7)
        sugarcaneMulti(s8, s8, s8)
        sugarcaneMulti(s9, s9, s9)
        sugarcaneMulti(s10, s10, s10)
        sugarcaneMulti(s11, s11, s11)
    if (sugerInstances == 12):
        sugercane()
        time.sleep(1)
        sugarcaneMulti(s2, s2, s2)
        time.sleep(1)
        sugarcaneMulti(s3, s3, s3)
        time.sleep(1)
        sugarcaneMulti(s4, s4, s4)
        time.sleep(1)
        sugarcaneMulti(s5, s5, s5)
        time.sleep(1)
        sugarcaneMulti(s6, s6, s6)
        time.sleep(1)
        sugarcaneMulti(s7, s7, s7)
        time.sleep(1)
        sugarcaneMulti(s8, s8, s8)
        time.sleep(1)
        sugarcaneMulti(s9, s9, s9)
        time.sleep(1)
        sugarcaneMulti(s10, s10, s10)
        time.sleep(1)
        sugarcaneMulti(s11, s11, s11)
        time.sleep(1)
        sugarcaneMulti(s12, s12, s12)
        time.sleep(1)
    if (sugerInstances == 13):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
        sugarcaneMulti(s4, s4, s4)
        sugarcaneMulti(s5, s5, s5)
        sugarcaneMulti(s6, s6, s6)
        sugarcaneMulti(s7, s7, s7)
        sugarcaneMulti(s8, s8, s8)
        sugarcaneMulti(s9, s9, s9)
        sugarcaneMulti(s10, s10, s10)
        sugarcaneMulti(s11, s11, s11)
        sugarcaneMulti(s12, s12, s12)
        sugarcaneMulti(s13, s13, s13)
    if (sugerInstances == 14):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
        sugarcaneMulti(s4, s4, s4)
        sugarcaneMulti(s5, s5, s5)
        sugarcaneMulti(s6, s6, s6)
        sugarcaneMulti(s7, s7, s7)
        sugarcaneMulti(s8, s8, s8)
        sugarcaneMulti(s9, s9, s9)
        sugarcaneMulti(s10, s10, s10)
        sugarcaneMulti(s11, s11, s11)
        sugarcaneMulti(s12, s12, s12)
        sugarcaneMulti(s13, s13, s13)
        sugarcaneMulti(s14, s14, s14)
    if (sugerInstances == 15):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
        sugarcaneMulti(s4, s4, s4)
        sugarcaneMulti(s5, s5, s5)
        sugarcaneMulti(s6, s6, s6)
        sugarcaneMulti(s7, s7, s7)
        sugarcaneMulti(s8, s8, s8)
        sugarcaneMulti(s9, s9, s9)
        sugarcaneMulti(s10, s10, s10)
        sugarcaneMulti(s11, s11, s11)
        sugarcaneMulti(s12, s12, s12)
        sugarcaneMulti(s13, s13, s13)
        sugarcaneMulti(s14, s14, s14)
        sugarcaneMulti(s15, s15, s15)
    if (sugerInstances == 16):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
        sugarcaneMulti(s4, s4, s4)
        sugarcaneMulti(s5, s5, s5)
        sugarcaneMulti(s6, s6, s6)
        sugarcaneMulti(s7, s7, s7)
        sugarcaneMulti(s8, s8, s8)
        sugarcaneMulti(s9, s9, s9)
        sugarcaneMulti(s10, s10, s10)
        sugarcaneMulti(s11, s11, s11)
        sugarcaneMulti(s12, s12, s12)
        sugarcaneMulti(s13, s13, s13)
        sugarcaneMulti(s14, s14, s14)
        sugarcaneMulti(s15, s15, s15)
        sugarcaneMulti(s16, s16, s16)
    if (sugerInstances == 17):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
        sugarcaneMulti(s4, s4, s4)
        sugarcaneMulti(s5, s5, s5)
        sugarcaneMulti(s6, s6, s6)
        sugarcaneMulti(s7, s7, s7)
        sugarcaneMulti(s8, s8, s8)
        sugarcaneMulti(s9, s9, s9)
        sugarcaneMulti(s10, s10, s10)
        sugarcaneMulti(s11, s11, s11)
        sugarcaneMulti(s12, s12, s12)
        sugarcaneMulti(s13, s13, s13)
        sugarcaneMulti(s14, s14, s14)
        sugarcaneMulti(s15, s15, s15)
        sugarcaneMulti(s16, s16, s16)
        sugarcaneMulti(s17, s17, s17)
    if (sugerInstances == 18):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
        sugarcaneMulti(s4, s4, s4)
        sugarcaneMulti(s5, s5, s5)
        sugarcaneMulti(s6, s6, s6)
        sugarcaneMulti(s7, s7, s7)
        sugarcaneMulti(s8, s8, s8)
        sugarcaneMulti(s9, s9, s9)
        sugarcaneMulti(s10, s10, s10)
        sugarcaneMulti(s11, s11, s11)
        sugarcaneMulti(s12, s12, s12)
        sugarcaneMulti(s13, s13, s13)
        sugarcaneMulti(s14, s14, s14)
        sugarcaneMulti(s15, s15, s15)
        sugarcaneMulti(s16, s16, s16)
        sugarcaneMulti(s17, s17, s17)
        sugarcaneMulti(s18, s18, s18)
    if (sugerInstances == 19):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
        sugarcaneMulti(s4, s4, s4)
        sugarcaneMulti(s5, s5, s5)
        sugarcaneMulti(s6, s6, s6)
        sugarcaneMulti(s7, s7, s7)
        sugarcaneMulti(s8, s8, s8)
        sugarcaneMulti(s9, s9, s9)
        sugarcaneMulti(s10, s10, s10)
        sugarcaneMulti(s11, s11, s11)
        sugarcaneMulti(s12, s12, s12)
        sugarcaneMulti(s13, s13, s13)
        sugarcaneMulti(s14, s14, s14)
        sugarcaneMulti(s15, s15, s15)
        sugarcaneMulti(s16, s16, s16)
        sugarcaneMulti(s17, s17, s17)
        sugarcaneMulti(s18, s18, s18)
        sugarcaneMulti(s19, s19, s19)
    if (sugerInstances == 20):
        sugercane()
        sugarcaneMulti(s2, s2, s2)
        sugarcaneMulti(s3, s3, s3)
        sugarcaneMulti(s4, s4, s4)
        sugarcaneMulti(s5, s5, s5)
        sugarcaneMulti(s6, s6, s6)
        sugarcaneMulti(s7, s7, s7)
        sugarcaneMulti(s8, s8, s8)
        sugarcaneMulti(s9, s9, s9)
        sugarcaneMulti(s10, s10, s10)
        sugarcaneMulti(s11, s11, s11)
        sugarcaneMulti(s12, s12, s12)
        sugarcaneMulti(s13, s13, s13)
        sugarcaneMulti(s14, s14, s14)
        sugarcaneMulti(s15, s15, s15)
        sugarcaneMulti(s16, s16, s16)
        sugarcaneMulti(s17, s17, s17)
        sugarcaneMulti(s18, s18, s18)
        sugarcaneMulti(s19, s19, s19)
        sugarcaneMulti(s20, s20, s20)

    if (wartInstances == 1 and sugerInstances == 0):
        wart()
    if (wartInstances == 1):
        wartMulti(w1, w1, w1)

    if (wartInstances == 2):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)


    if (wartInstances == 3):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)

    if (wartInstances == 4):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)
        wartMulti(w4, w4, w4)


    if (wartInstances == 5):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)
        wartMulti(w4, w4, w4)
        wartMulti(w5, w5, w5)


    if (wartInstances == 6):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)
        wartMulti(w4, w4, w4)
        wartMulti(w5, w5, w5)
        wartMulti(w6, w6, w6)


    if (wartInstances == 7):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)
        wartMulti(w4, w4, w4)
        wartMulti(w5, w5, w5)
        wartMulti(w6, w6, w6)
        wartMulti(w7, w7, w7)


    if (wartInstances == 8):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)
        wartMulti(w4, w4, w4)
        wartMulti(w5, w5, w5)
        wartMulti(w6, w6, w6)
        wartMulti(w7, w7, w7)
        wartMulti(w8, w8, w8)


    if (wartInstances == 9):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)
        wartMulti(w4, w4, w4)
        wartMulti(w5, w5, w5)
        wartMulti(w6, w6, w6)
        wartMulti(w7, w7, w7)
        wartMulti(w8, w8, w8)
        wartMulti(w9, w9, w9)


    if (wartInstances == 10):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)
        wartMulti(w4, w4, w4)
        wartMulti(w5, w5, w5)
        wartMulti(w6, w6, w6)
        wartMulti(w7, w7, w7)
        wartMulti(w8, w8, w8)
        wartMulti(w9, w9, w9)
        wartMulti(w10, w10, w10)


    if (wartInstances == 11):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)
        wartMulti(w4, w4, w4)
        wartMulti(w5, w5, w5)
        wartMulti(w6, w6, w6)
        wartMulti(w7, w7, w7)
        wartMulti(w8, w8, w8)
        wartMulti(w9, w9, w9)
        wartMulti(w10, w10, w10)
        wartMulti(w11, w11, w11)


    if (wartInstances == 12):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)
        wartMulti(w4, w4, w4)
        wartMulti(w5, w5, w5)
        wartMulti(w6, w6, w6)
        wartMulti(w7, w7, w7)
        wartMulti(w8, w8, w8)
        wartMulti(w9, w9, w9)
        wartMulti(w10, w10, w10)
        wartMulti(w11, w11, w11)
        wartMulti(w12, w12, w12)

    if (wartInstances == 13):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)
        wartMulti(w4, w4, w4)
        wartMulti(w5, w5, w5)
        wartMulti(w6, w6, w6)
        wartMulti(w7, w7, w7)
        wartMulti(w8, w8, w8)
        wartMulti(w9, w9, w9)
        wartMulti(w10, w10, w10)
        wartMulti(w11, w11, w11)
        wartMulti(w12, w12, w12)
        wartMulti(w13, w13, w13)

    if (wartInstances == 14):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)
        wartMulti(w4, w4, w4)
        wartMulti(w5, w5, w5)
        wartMulti(w6, w6, w6)
        wartMulti(w7, w7, w7)
        wartMulti(w8, w8, w8)
        wartMulti(w9, w9, w9)
        wartMulti(w10, w10, w10)
        wartMulti(w11, w11, w11)
        wartMulti(w12, w12, w12)
        wartMulti(w13, w13, w13)
        wartMulti(w14, w14, w14)

    if (wartInstances == 15):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)
        wartMulti(w4, w4, w4)
        wartMulti(w5, w5, w5)
        wartMulti(w6, w6, w6)
        wartMulti(w7, w7, w7)
        wartMulti(w8, w8, w8)
        wartMulti(w9, w9, w9)
        wartMulti(w10, w10, w10)
        wartMulti(w11, w11, w11)
        wartMulti(w12, w12, w12)
        wartMulti(w13, w13, w13)
        wartMulti(w14, w14, w14)
        wartMulti(w15, w15, w15)


    if (wartInstances == 16):
        wartMulti(w1, w1, w1)

        wartMulti(w2, w2, w2)

        wartMulti(w3, w3, w3)

        wartMulti(w4, w4, w4)

        wartMulti(w5, w5, w5)

        wartMulti(w6, w6, w6)

        wartMulti(w7, w7, w7)

        wartMulti(w8, w8, w8)

        wartMulti(w9, w9, w9)

        wartMulti(w10, w10, w10)

        wartMulti(w11, w11, w11)

        wartMulti(w12, w12, w12)

        wartMulti(w13, w13, w13)

        wartMulti(w14, w14, w14)

        wartMulti(w15, w15, w15)

        wartMulti(w16, w16, w16)


    if (wartInstances == 17):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)
        wartMulti(w4, w4, w4)
        wartMulti(w5, w5, w5)
        wartMulti(w6, w6, w6)
        wartMulti(w7, w7, w7)
        wartMulti(w8, w8, w8)
        wartMulti(w9, w9, w9)
        wartMulti(w10, w10, w10)
        wartMulti(w11, w11, w11)
        wartMulti(w12, w12, w12)
        wartMulti(w13, w13, w13)
        wartMulti(w14, w14, w14)
        wartMulti(w15, w15, w15)
        wartMulti(w16, w16, w16)
        wartMulti(w17, w17, w17)

    if (wartInstances == 18):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)
        wartMulti(w4, w4, w4)
        wartMulti(w5, w5, w5)
        wartMulti(w6, w6, w6)
        wartMulti(w7, w7, w7)
        wartMulti(w8, w8, w8)
        wartMulti(w9, w9, w9)
        wartMulti(w10, w10, w10)
        wartMulti(w11, w11, w11)
        wartMulti(w12, w12, w12)
        wartMulti(w13, w13, w13)
        wartMulti(w14, w14, w14)
        wartMulti(w15, w15, w15)
        wartMulti(w16, w16, w16)
        wartMulti(w17, w17, w17)
        wartMulti(w18, w18, w18)

    if (wartInstances == 19):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)
        wartMulti(w4, w4, w4)
        wartMulti(w5, w5, w5)
        wartMulti(w6, w6, w6)
        wartMulti(w7, w7, w7)
        wartMulti(w8, w8, w8)
        wartMulti(w9, w9, w9)
        wartMulti(w10, w10, w10)
        wartMulti(w11, w11, w11)
        wartMulti(w12, w12, w12)
        wartMulti(w13, w13, w13)
        wartMulti(w14, w14, w14)
        wartMulti(w15, w15, w15)
        wartMulti(w16, w16, w16)
        wartMulti(w17, w17, w17)
        wartMulti(w18, w18, w18)
        wartMulti(w19, w19, w19)

    if (wartInstances == 20):
        wartMulti(w1, w1, w1)
        wartMulti(w2, w2, w2)
        wartMulti(w3, w3, w3)
        wartMulti(w4, w4, w4)
        wartMulti(w5, w5, w5)
        wartMulti(w6, w6, w6)
        wartMulti(w7, w7, w7)
        wartMulti(w8, w8, w8)
        wartMulti(w9, w9, w9)
        wartMulti(w10, w10, w10)
        wartMulti(w11, w11, w11)
        wartMulti(w12, w12, w12)
        wartMulti(w13, w13, w13)
        wartMulti(w14, w14, w14)
        wartMulti(w15, w15, w15)
        wartMulti(w16, w16, w16)
        wartMulti(w17, w17, w17)
        wartMulti(w18, w18, w18)
        wartMulti(w19, w19, w19)
        wartMulti(w20, w20, w20)

    time.sleep(terminationTimer)
    for i in range (accountNumber +1):
        termination()